### ISSUE TITLE
最新版本代码中SysHash2BlockInfoService类中，将创建sys_hash_2_block表的方法注释掉了

### ISSUE THREAD

**Issue by xxmlovezw** [WeBankBlockchain/Data-Stash#27]
@Override
	@Transactional
	public void createSchema() {
	    //mapper.createTable(DBStaticTableConstants.SYS_HASH_2_BLOCK_TABLE);

		String detailTableName = DBStaticTableConstants.SYS_HASH_2_BLOCK_TABLE + DBStaticTableConstants.SYS_DETAIL_TABLE_POST_FIX;
		mapper.createDetailTable(detailTableName);
	}

**Comment by arc0035** [comment]
这张表不需要的
