### ISSUE TITLE
data-stash数据备份的时候分库分表源码执行报错，经查询源码中replace和insert调用问题，导致无法写数据进表，烦请解答

### ISSUE THREAD

**Issue by Esther-xs** [WeBankBlockchain/Data-Stash#29]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement cannot be cast to org.apache.shardingsphere.sql.parser.sql.statement.dml.ReplaceStatement

![4861658399157_ pic](https://user-images.githubusercontent.com/68682956/180201547-88c8e0a4-d080-46c0-9668-6c6c6da602b6.jpg)
![4871658399291_ pic](https://user-images.githubusercontent.com/68682956/180201560-6dd8cc0b-e3e1-4cca-8f0b-1fd188ddc084.jpg)

**Comment by arc0035** [comment]
麻烦提供下分库分表配置，并且尝试下dev分支是否存在此问题

**Comment by Esther-xs** [comment]
分库分表配置我参考了官方文档示例：https://data-doc.readthedocs.io/zh_CN/latest/docs/WeBankBlockchain-Data-Stash/advance.html#id2 

以下是我的配置：
### 配置nginx服务的binlog地址，如果连接多个节点的话，使用逗号分隔
system.binlogAddress=http://127.0.0.1:5299/

### 分库分表配置
#### 打开开关
spring.shardingsphere.enabled=true
#### 定义数据源
spring.shardingsphere.datasource.names = stash1,stash2
spring.shardingsphere.datasource.stash1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.stash1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.stash1.jdbcUrl=jdbc:mysql://localhost:3306/stash1?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.stash1.username=root
spring.shardingsphere.datasource.stash1.password=123456

spring.shardingsphere.datasource.stash2.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.stash2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.stash2.jdbcUrl=jdbc:mysql://localhost:3306/stash2?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.stash2.username=root
spring.shardingsphere.datasource.stash2.password=123456

#### 不做分片的表，默认存储到stash1
spring.shardingsphere.sharding.default-data-source-name=stash1

#### 需分片的表，路由目标
spring.shardingsphere.sharding.tables._sys_hash_2_block_.actual‐data‐nodes = stash$->{1..2}._sys_hash_2_block_
spring.shardingsphere.sharding.tables._sys_hash_2_block_d_.actual‐data‐nodes = stash$->{1..2}._sys_hash_2_block_d_
spring.shardingsphere.sharding.tables._sys_tx_hash_2_block_.actual‐data‐nodes = stash$->{1..2}._sys_tx_hash_2_block_
spring.shardingsphere.sharding.tables._sys_tx_hash_2_block_d_.actual‐data‐nodes = stash$->{1..2}._sys_tx_hash_2_block_d_

#### 需分片的表，分片策略
spring.shardingsphere.sharding.default-database-strategy.standard.sharding-column= _num_
spring.shardingsphere.sharding.default-database-strategy.standard.precise-algorithm-class-name=com.webank.blockchain.data.stash.db.sharding.BlockShardingAlgorithm
spring.shardingsphere.sharding.default-database-strategy.standard.range-algorithm-class-name=com.webank.blockchain.data.stash.db.sharding.BlockShardingAlgorithm
#spring.shardingsphere.props.sql.show = false

### logback配置
#logging.file=./logs/stash.log
#logging.level.com.webank=INFO

—————————————————————————————
此外还有一点疑问，执行分库分表导出的时候，再在新节点上执行data_sync同步的时候，是分两个库导入，还是两个库一次性导入，如果一次性导入~/data-sync-bash/config.conf如何配置呢？（官方文档只有单库导入的配置示例）

**Comment by Esther-xs** [comment]
> 麻烦提供下分库分表配置，并且尝试下dev分支是否存在此问题

分库分表配置我参考了官方文档示例：https://data-doc.readthedocs.io/zh_CN/latest/docs/WeBankBlockchain-Data-Stash/advance.html#id2 

以下是我的配置：
### 配置nginx服务的binlog地址，如果连接多个节点的话，使用逗号分隔
system.binlogAddress=http://127.0.0.1:5299/

### 分库分表配置
#### 打开开关
spring.shardingsphere.enabled=true
#### 定义数据源
spring.shardingsphere.datasource.names = stash1,stash2
spring.shardingsphere.datasource.stash1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.stash1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.stash1.jdbcUrl=jdbc:mysql://localhost:3306/stash1?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.stash1.username=root
spring.shardingsphere.datasource.stash1.password=123456

spring.shardingsphere.datasource.stash2.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.stash2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.stash2.jdbcUrl=jdbc:mysql://localhost:3306/stash2?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.stash2.username=root
spring.shardingsphere.datasource.stash2.password=123456

#### 不做分片的表，默认存储到stash1
spring.shardingsphere.sharding.default-data-source-name=stash1

#### 需分片的表，路由目标
spring.shardingsphere.sharding.tables._sys_hash_2_block_.actual‐data‐nodes = stash$->{1..2}._sys_hash_2_block_
spring.shardingsphere.sharding.tables._sys_hash_2_block_d_.actual‐data‐nodes = stash$->{1..2}._sys_hash_2_block_d_
spring.shardingsphere.sharding.tables._sys_tx_hash_2_block_.actual‐data‐nodes = stash$->{1..2}._sys_tx_hash_2_block_
spring.shardingsphere.sharding.tables._sys_tx_hash_2_block_d_.actual‐data‐nodes = stash$->{1..2}._sys_tx_hash_2_block_d_

#### 需分片的表，分片策略
spring.shardingsphere.sharding.default-database-strategy.standard.sharding-column= _num_
spring.shardingsphere.sharding.default-database-strategy.standard.precise-algorithm-class-name=com.webank.blockchain.data.stash.db.sharding.BlockShardingAlgorithm
spring.shardingsphere.sharding.default-database-strategy.standard.range-algorithm-class-name=com.webank.blockchain.data.stash.db.sharding.BlockShardingAlgorithm
#spring.shardingsphere.props.sql.show = false

### logback配置
#logging.file=./logs/stash.log
#logging.level.com.webank=INFO

—————————————————————————————
此外还有一点疑问，执行分库分表导出的时候，再在新节点上执行data_sync同步的时候，是分两个库导入，还是两个库一次性导入，如果一次性导入~/data-sync-bash/config.conf如何配置呢？（官方文档只有单库导入的配置示例）
![Uploading 截屏2022-07-22 15.09.44.png…]()

**Comment by Esther-xs** [comment]
> 麻烦提供下分库分表配置，并且尝试下dev分支是否存在此问题

分库分表配置我参考了官方文档示例：https://data-doc.readthedocs.io/zh_CN/latest/docs/WeBankBlockchain-Data-Stash/advance.html#id2 

以下是我的配置：
### 配置nginx服务的binlog地址，如果连接多个节点的话，使用逗号分隔
system.binlogAddress=http://127.0.0.1:5299/
### 分库分表配置
#### 打开开关
spring.shardingsphere.enabled=true
#### 定义数据源
spring.shardingsphere.datasource.names = stash1,stash2
spring.shardingsphere.datasource.stash1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.stash1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.stash1.jdbcUrl=jdbc:mysql://localhost:3306/stash1?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.stash1.username=root
spring.shardingsphere.datasource.stash1.password=123456

spring.shardingsphere.datasource.stash2.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.stash2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.stash2.jdbcUrl=jdbc:mysql://localhost:3306/stash2?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.stash2.username=root
spring.shardingsphere.datasource.stash2.password=123456

#### 不做分片的表，默认存储到stash1
spring.shardingsphere.sharding.default-data-source-name=stash1

#### 需分片的表，路由目标
spring.shardingsphere.sharding.tables._sys_hash_2_block_.actual‐data‐nodes = stash$->{1..2}._sys_hash_2_block_
spring.shardingsphere.sharding.tables._sys_hash_2_block_d_.actual‐data‐nodes = stash$->{1..2}._sys_hash_2_block_d_
spring.shardingsphere.sharding.tables._sys_tx_hash_2_block_.actual‐data‐nodes = stash$->{1..2}._sys_tx_hash_2_block_
spring.shardingsphere.sharding.tables._sys_tx_hash_2_block_d_.actual‐data‐nodes = stash$->{1..2}._sys_tx_hash_2_block_d_

#### 需分片的表，分片策略
spring.shardingsphere.sharding.default-database-strategy.standard.sharding-column= _num_
spring.shardingsphere.sharding.default-database-strategy.standard.precise-algorithm-class-name=com.webank.blockchain.data.stash.db.sharding.BlockShardingAlgorithm
spring.shardingsphere.sharding.default-database-strategy.standard.range-algorithm-class-name=com.webank.blockchain.data.stash.db.sharding.BlockShardingAlgorithm
#spring.shardingsphere.props.sql.show = false

### logback配置
#logging.file=./logs/stash.log
#logging.level.com.webank=INFO

—————————————————————————————
此外还有一点疑问，执行分库分表导出的时候，再在新节点上执行data_sync同步的时候，是分两个库导入，还是两个库一次性导入，如果一次性导入~/data-sync-bash/config.conf如何配置呢？（官方文档只有单库导入的配置示例）
<img width="927" alt="截屏2022-07-22 15 09 44" src="https://user-images.githubusercontent.com/68682956/180385439-57e5ca58-44d7-451a-a78d-99413dcc39c9.png">

**Comment by arc0035** [comment]
好的，我们看一下

**Comment by Esther-xs** [comment]
【此外还有一点疑问，执行分库分表导出的时候，再在新节点上执行data_sync同步的时候，是分两个库导入，还是两个库一次性导入，想问下**多库导入如何配置**~/data-sync-bash/config.conf？（官方文档只有单库导入的配置示例）】

单库导入示例：
[stash]
stash.ip=127.0.0.1
stash.port=3306
stash.dbname=stash
stash.username=root
stash.password=123456

[node]
#要导出的群组ID，会根据配置读取节点目录conf/下指定group.id.ini配置，进行数据同步
node.groupId=1
#节点路径，若选择在fisco对应节点目录下(如~/fisco/nodes/127.0.0.1/node0)执行下述步骤，则无需配置节点路径，默认即可。
node.path=./

[more]
#同步截止区块号，如默认为10000，则同步0-9999号区块至新节点，后续区块将从其他节点同步拉取
sync.endBlockNumber=10000

**Comment by Esther-xs** [comment]
> 好的，我们看一下

【此外还有一点疑问，执行分库分表导出的时候，再在新节点上执行data_sync同步的时候，是分两个库导入，还是两个库一次性导入，想问下**多库导入如何配置**~/data-sync-bash/config.conf？（官方文档只有单库导入的配置示例）】

单库导入示例：
[stash]
stash.ip=127.0.0.1
stash.port=3306
stash.dbname=stash
stash.username=root
stash.password=123456

[node]
#要导出的群组ID，会根据配置读取节点目录conf/下指定group.id.ini配置，进行数据同步
node.groupId=1
#节点路径，若选择在fisco对应节点目录下(如~/fisco/nodes/127.0.0.1/node0)执行下述步骤，则无需配置节点路径，默认即可。
node.path=./

[more]
#同步截止区块号，如默认为10000，则同步0-9999号区块至新节点，后续区块将从其他节点同步拉取
sync.endBlockNumber=10000

**Comment by arc0035** [comment]
您好，针对您提出的两个问题：
1）replace into在分库分表报错：经确认，确实存在此问题
2）关于data-sync-bash对分库分表的支持：目前还未支持。
分库分表目前还处于实验阶段，只进行了初步的支持，还很不完善，预计下个版本会进行修复。感谢反馈！
