### ISSUE TITLE
gradle打包配置有问题，执行tools/start.sh脚本时bootJar打包失效，dist/Data-Stash.jar编译生成后会被tools中的覆盖

### ISSUE THREAD

**Issue by yingbaohuacumt** [WeBankBlockchain/Data-Stash#31]
![image](https://user-images.githubusercontent.com/40226586/183955755-e4be0c31-19e1-4416-89bd-c8a67f7b42ef.png)

执行tools/start.sh编译成功一次后，再次编译dist目录新生成jar包会被tools路径下的覆盖，bootJar配置有问题

**Comment by arc0035** [comment]
可否提供一下完整的操作步骤？

**Comment by arc0035** [comment]
fixed in dd_1.2.4
