### ISSUE TITLE
数据裁剪之后，如何通过 stash 查询冷数据？

### ISSUE THREAD

**Issue by Youbaiwan** [WeBankBlockchain/Data-Stash#33]
![image](https://user-images.githubusercontent.com/49031861/187865143-ce1affef-d19e-438b-ab37-a8e3a4409e5f.png)
删掉部分冷数据之后，通过控制台查询区块数据:  getBlockByNumber, getTransactionByBlockNumberAndIndex 等，并没有去通过 stash 查询。所以，要怎么从 stash 查询数据呢？

**Comment by dalaocu** [comment]
状态数据并不会被链删除。只有详细的区块数据才会从stash去拉取。
